import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service.js';
import type { CreateAttributeDto, CreateOptionDto, UpdateAttributeDto, UpdateOptionDto } from './catalog.dto.js';
@Injectable()
export class AttributesService {
  constructor(private readonly prisma: PrismaService) {}
  async create(dto: CreateAttributeDto) { try { const { translations, ...data } = dto; return await this.prisma.attributeDefinition.create({ data: { ...data, minValue: data.minValue ?? null, maxValue: data.maxValue ?? null, defaultValue: data.defaultValue as never, translations: { create: translations.map((item) => ({ locale: item.locale, label: item.label, description: item.description ?? null, unit: item.unit ?? null })) } } as never, include: { translations: true } }); } catch { throw new ConflictException('Attribute key or translation locale already exists'); } }
  async update(id: string, dto: UpdateAttributeDto) { await this.ensure(id); const { translations, ...data } = dto; return this.prisma.$transaction(async (tx) => { await tx.attributeDefinition.update({ where: { id }, data: data as never }); if (translations) for (const item of translations) await tx.attributeTranslation.upsert({ where: { attributeId_locale: { attributeId: id, locale: item.locale } }, update: { label: item.label, description: item.description ?? null, unit: item.unit ?? null, deletedAt: null }, create: { attributeId: id, locale: item.locale, label: item.label, description: item.description ?? null, unit: item.unit ?? null } }); return tx.attributeDefinition.findUniqueOrThrow({ where: { id }, include: { translations: true, options: { where: { deletedAt: null }, include: { translations: true } } } }); }); }
  async remove(id: string) { await this.ensure(id); const now = new Date(); await this.prisma.$transaction([this.prisma.attributeDefinition.update({ where: { id }, data: { deletedAt: now, isActive: false } }), this.prisma.attributeTranslation.updateMany({ where: { attributeId: id }, data: { deletedAt: now } }), this.prisma.attributeOption.updateMany({ where: { attributeId: id }, data: { deletedAt: now, isActive: false } }), this.prisma.categoryAttribute.updateMany({ where: { attributeId: id }, data: { deletedAt: now } })]); return { deleted: true }; }
  async createOption(attributeId: string, dto: CreateOptionDto) { await this.ensure(attributeId); const { translations, ...data } = dto; return this.prisma.attributeOption.create({ data: { attributeId, ...data, translations: { create: translations.map((item) => ({ locale: item.locale, label: item.label })) } }, include: { translations: true } }); }
  async updateOption(attributeId: string, optionId: string, dto: UpdateOptionDto) { await this.ensureOption(attributeId, optionId); const { translations, ...data } = dto; return this.prisma.$transaction(async (tx) => { await tx.attributeOption.update({ where: { id: optionId }, data }); if (translations) for (const item of translations) await tx.attributeOptionTranslation.upsert({ where: { optionId_locale: { optionId, locale: item.locale } }, update: { label: item.label, deletedAt: null }, create: { optionId, locale: item.locale, label: item.label } }); return tx.attributeOption.findUniqueOrThrow({ where: { id: optionId }, include: { translations: true } }); }); }
  async removeOption(attributeId: string, optionId: string) { await this.ensureOption(attributeId, optionId); const now = new Date(); await this.prisma.$transaction([this.prisma.attributeOption.update({ where: { id: optionId }, data: { deletedAt: now, isActive: false } }), this.prisma.attributeOptionTranslation.updateMany({ where: { optionId }, data: { deletedAt: now } })]); return { deleted: true }; }
  private async ensure(id: string) { const row = await this.prisma.attributeDefinition.findFirst({ where: { id, deletedAt: null } }); if (!row) throw new NotFoundException('Attribute not found'); return row; }
  private async ensureOption(attributeId: string, id: string) { const row = await this.prisma.attributeOption.findFirst({ where: { id, attributeId, deletedAt: null } }); if (!row) throw new NotFoundException('Attribute option not found'); return row; }
}
