import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service.js';
import type { CreateBrandDto, CreateBrandModelDto, UpdateBrandDto, UpdateBrandModelDto } from './catalog.dto.js';
const brandInclude = { translations: { where: { deletedAt: null } }, models: { where: { deletedAt: null, isActive: true }, orderBy: { sortOrder: 'asc' as const }, include: { translations: { where: { deletedAt: null } } } } } as const;
@Injectable()
export class BrandsService {
  constructor(private readonly prisma: PrismaService) {}
  list(locale?: string) { return this.prisma.brand.findMany({ where: { deletedAt: null, isActive: true }, orderBy: [{ sortOrder: 'asc' }, { slug: 'asc' }], include: { translations: { where: { deletedAt: null, ...(locale ? { locale } : {}) } } } }); }
  one(id: string) { return this.prisma.brand.findFirstOrThrow({ where: { id, deletedAt: null, isActive: true }, include: brandInclude }); }
  models(id: string) { return this.prisma.brandModel.findMany({ where: { brandId: id, deletedAt: null, isActive: true }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { deletedAt: null } } } }); }
  async create(dto: CreateBrandDto) { const { translations, categoryIds, ...data } = dto; try { return await this.prisma.brand.create({ data: { ...data, logoId: data.logoId ?? null, translations: { create: translations }, categories: categoryIds ? { create: categoryIds.map((categoryId) => ({ categoryId })) } : undefined } as never, include: brandInclude }); } catch { throw new ConflictException('Brand slug or relation already exists'); } }
  async update(id: string, dto: UpdateBrandDto) { await this.ensure(id); const { translations, categoryIds, ...data } = dto; return this.prisma.$transaction(async (tx) => { await tx.brand.update({ where: { id }, data }); if (translations) for (const item of translations) await tx.brandTranslation.upsert({ where: { brandId_locale: { brandId: id, locale: item.locale } }, update: { name: item.name, deletedAt: null }, create: { brandId: id, locale: item.locale, name: item.name } }); if (categoryIds) for (const categoryId of categoryIds) await tx.categoryBrand.upsert({ where: { categoryId_brandId: { categoryId, brandId: id } }, update: { deletedAt: null }, create: { categoryId, brandId: id } }); return tx.brand.findUniqueOrThrow({ where: { id }, include: brandInclude }); }); }
  async remove(id: string) { await this.ensure(id); const now = new Date(); await this.prisma.$transaction([this.prisma.brand.update({ where: { id }, data: { deletedAt: now, isActive: false } }), this.prisma.brandTranslation.updateMany({ where: { brandId: id }, data: { deletedAt: now } }), this.prisma.brandModel.updateMany({ where: { brandId: id }, data: { deletedAt: now, isActive: false } }), this.prisma.categoryBrand.updateMany({ where: { brandId: id }, data: { deletedAt: now } })]); return { deleted: true }; }
  async createModel(brandId: string, dto: CreateBrandModelDto) { await this.ensure(brandId); const { translations, ...data } = dto; return this.prisma.brandModel.create({ data: { brandId, ...data, translations: { create: translations } }, include: { translations: true } }); }
  async updateModel(brandId: string, modelId: string, dto: UpdateBrandModelDto) { await this.ensureModel(brandId, modelId); const { translations, ...data } = dto; return this.prisma.$transaction(async (tx) => { await tx.brandModel.update({ where: { id: modelId }, data }); if (translations) for (const item of translations) await tx.brandModelTranslation.upsert({ where: { modelId_locale: { modelId, locale: item.locale } }, update: { name: item.name, deletedAt: null }, create: { modelId, locale: item.locale, name: item.name } }); return tx.brandModel.findUniqueOrThrow({ where: { id: modelId }, include: { translations: true } }); }); }
  async removeModel(brandId: string, modelId: string) { await this.ensureModel(brandId, modelId); const now = new Date(); await this.prisma.$transaction([this.prisma.brandModel.update({ where: { id: modelId }, data: { deletedAt: now, isActive: false } }), this.prisma.brandModelTranslation.updateMany({ where: { modelId }, data: { deletedAt: now } })]); return { deleted: true }; }
  private async ensure(id: string) { const row = await this.prisma.brand.findFirst({ where: { id, deletedAt: null } }); if (!row) throw new NotFoundException('Brand not found'); return row; }
  private async ensureModel(brandId: string, id: string) { const row = await this.prisma.brandModel.findFirst({ where: { id, brandId, deletedAt: null } }); if (!row) throw new NotFoundException('Brand model not found'); return row; }
}
