/* eslint-disable @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access */
import { BadRequestException, ValidationPipe } from '@nestjs/common';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import * as argon2 from 'argon2';
import { AppModule } from '../app.module.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { seedCatalog } from '../../prisma/catalog.seed.js';

describe('Catalog integration', () => {
  let app: INestApplication; let prisma: PrismaService; let ownerToken = ''; let userToken = '';
  const suffix = Date.now().toString(); const password = 'CatalogPassword123!';
  beforeAll(async () => {
    const module = await Test.createTestingModule({ imports: [AppModule] }).compile(); app = module.createNestApplication(); app.setGlobalPrefix('api/v1'); app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true, exceptionFactory: () => new BadRequestException('Validation failed') })); await app.init(); prisma = app.get(PrismaService);
    for (const roleName of ['OWNER', 'USER']) { const email = `catalog-${roleName.toLowerCase()}-${suffix}@example.com`; const role = await prisma.role.findUniqueOrThrow({ where: { name: roleName } }); const user = await prisma.user.create({ data: { email, normalizedEmail: email, passwordHash: await argon2.hash(password), status: 'ACTIVE', emailVerifiedAt: new Date(), userRoles: { create: { roleId: role.id } } } }); expect(user.id).toBeTruthy(); const login = await request(app.getHttpServer()).post('/api/v1/auth/login').send({ email, password }).expect(201); if (roleName === 'OWNER') ownerToken = login.body.accessToken as string; else userToken = login.body.accessToken as string; }
  });
  afterAll(async () => { await prisma.category.deleteMany({ where: { slug: { in: [`cycle-child-${suffix}`, `delete-child-${suffix}`] } } }); await prisma.category.deleteMany({ where: { slug: { in: [`test-category-${suffix}`, `cycle-parent-${suffix}`, `delete-parent-${suffix}`] } } }); await prisma.attributeDefinition.deleteMany({ where: { key: `testAttr${suffix}` } }); await prisma.brand.deleteMany({ where: { slug: `test-brand-${suffix}` } }); await prisma.user.deleteMany({ where: { normalizedEmail: { in: [`catalog-owner-${suffix}@example.com`, `catalog-user-${suffix}@example.com`] } } }); await app.close(); });
  const auth = () => ({ Authorization: `Bearer ${ownerToken}` });
  const translations = (name: string) => ['ru', 'en', 'hy'].map((locale) => ({ locale, name: `${name}-${locale}` }));

  it('returns the full localized category tree with nesting', async () => { const response = await request(app.getHttpServer()).get('/api/v1/categories/tree?locale=hy').expect(200); const roots = response.body as Array<{ slug: string; children: unknown[]; translations: Array<{ locale: string }> }>; const seeded = ['transport','real-estate','jobs','services','electronics','home-garden','personal-items','hobbies-leisure','animals','business-equipment']; expect(seeded.every((slug) => roots.some((item) => item.slug === slug))).toBe(true); const transport = roots.find((item) => item.slug === 'transport')!; expect(transport.children.length).toBeGreaterThan(0); expect(transport.translations[0]!.locale).toBe('hy'); });
  it('gets categories by id and slug and exposes attributes/brands', async () => { const car = await request(app.getHttpServer()).get('/api/v1/categories/slug/cars').expect(200); await request(app.getHttpServer()).get(`/api/v1/categories/${car.body.id}`).expect(200); const attrs = await request(app.getHttpServer()).get(`/api/v1/categories/${car.body.id}/attributes`).expect(200); const brands = await request(app.getHttpServer()).get(`/api/v1/categories/${car.body.id}/brands`).expect(200); expect(attrs.body.length).toBe(12); expect(brands.body.length).toBe(3); });
  it('creates, updates and rejects duplicate slugs', async () => { const slug = `test-category-${suffix}`; const created = await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug, translations: translations('Test') }).expect(201); await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug, translations: translations('Duplicate') }).expect(409); const updated = await request(app.getHttpServer()).patch(`/api/v1/admin/categories/${created.body.id}`).set(auth()).send({ isFeatured: true, translations: translations('Updated') }).expect(200); expect(updated.body.isFeatured).toBe(true); });
  it('prevents self-parenting and cyclic nesting', async () => { const parent = await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug: `cycle-parent-${suffix}`, translations: translations('Parent') }).expect(201); await request(app.getHttpServer()).patch(`/api/v1/admin/categories/${parent.body.id}`).set(auth()).send({ parentId: parent.body.id }).expect(400); const child = await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug: `cycle-child-${suffix}`, parentId: parent.body.id, translations: translations('Child') }).expect(201); await request(app.getHttpServer()).patch(`/api/v1/admin/categories/${parent.body.id}`).set(auth()).send({ parentId: child.body.id }).expect(400); });
  it('requires force for active children and supports restore', async () => { const parent = await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug: `delete-parent-${suffix}`, translations: translations('Parent') }).expect(201); await request(app.getHttpServer()).post('/api/v1/admin/categories').set(auth()).send({ slug: `delete-child-${suffix}`, parentId: parent.body.id, translations: translations('Child') }).expect(201); await request(app.getHttpServer()).delete(`/api/v1/admin/categories/${parent.body.id}`).set(auth()).expect(409); await request(app.getHttpServer()).delete(`/api/v1/admin/categories/${parent.body.id}?force=true`).set(auth()).expect(200); await request(app.getHttpServer()).post(`/api/v1/admin/categories/${parent.body.id}/restore`).set(auth()).expect(201); });
  it('creates attributes, options and category assignments', async () => { const attribute = await request(app.getHttpServer()).post('/api/v1/admin/attributes').set(auth()).send({ key: `testAttr${suffix}`, type: 'SINGLE_SELECT', filterable: true, translations: translations('Attribute').map(({ locale, name }) => ({ locale, label: name })) }).expect(201); const option = await request(app.getHttpServer()).post(`/api/v1/admin/attributes/${attribute.body.id}/options`).set(auth()).send({ value: 'one', translations: translations('One').map(({ locale, name }) => ({ locale, label: name })) }).expect(201); await request(app.getHttpServer()).patch(`/api/v1/admin/attributes/${attribute.body.id}/options/${option.body.id}`).set(auth()).send({ sortOrder: 2 }).expect(200); const cars = await prisma.category.findUniqueOrThrow({ where: { slug: 'cars' } }); await request(app.getHttpServer()).post(`/api/v1/admin/categories/${cars.id}/attributes`).set(auth()).send({ attributeId: attribute.body.id }).expect(201); await request(app.getHttpServer()).delete(`/api/v1/admin/categories/${cars.id}/attributes/${attribute.body.id}`).set(auth()).expect(200); await request(app.getHttpServer()).delete(`/api/v1/admin/attributes/${attribute.body.id}`).set(auth()).expect(200); });
  it('creates brands and models and soft deletes them', async () => { const brand = await request(app.getHttpServer()).post('/api/v1/admin/brands').set(auth()).send({ slug: `test-brand-${suffix}`, translations: translations('Brand') }).expect(201); const model = await request(app.getHttpServer()).post(`/api/v1/admin/brands/${brand.body.id}/models`).set(auth()).send({ slug: `model-${suffix}`, translations: translations('Model') }).expect(201); await request(app.getHttpServer()).get(`/api/v1/brands/${brand.body.id}/models`).expect(200); await request(app.getHttpServer()).patch(`/api/v1/admin/brands/${brand.body.id}/models/${model.body.id}`).set(auth()).send({ sortOrder: 3 }).expect(200); await request(app.getHttpServer()).delete(`/api/v1/admin/brands/${brand.body.id}/models/${model.body.id}`).set(auth()).expect(200); await request(app.getHttpServer()).delete(`/api/v1/admin/brands/${brand.body.id}`).set(auth()).expect(200); });
  it('allows public reads but denies USER catalog mutations', async () => { await request(app.getHttpServer()).get('/api/v1/categories').expect(200); await request(app.getHttpServer()).post('/api/v1/admin/categories').set('Authorization', `Bearer ${userToken}`).send({ slug: `forbidden-${suffix}`, translations: translations('Forbidden') }).expect(403); });
  it('catalog seed is repeatable without duplicates', async () => { const before = await prisma.category.count(); await seedCatalog(prisma); await seedCatalog(prisma); const after = await prisma.category.count(); expect(after).toBe(before); expect(await prisma.categoryTranslation.count({ where: { category: { slug: 'cars' } } })).toBe(3); }, 120_000);
});
