import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service.js';
import type { AttachAttributeDto, CreateCategoryDto, ReorderCategoriesDto, UpdateCategoryDto } from './catalog.dto.js';

const categoryInclude = { translations: { where: { deletedAt: null } }, children: { where: { deletedAt: null, isActive: true }, orderBy: { sortOrder: 'asc' as const }, include: { translations: { where: { deletedAt: null } } } } } as const;
@Injectable()
export class CategoriesService {
  constructor(private readonly prisma: PrismaService) {}
  list(locale?: string) { return this.prisma.category.findMany({ where: { deletedAt: null, isActive: true }, orderBy: [{ sortOrder: 'asc' }, { slug: 'asc' }], include: { translations: { where: { deletedAt: null, ...(locale ? { locale } : {}) } } } }); }
  async tree(locale?: string) {
    const rows = await this.list(locale); const map = new Map(rows.map((row) => [row.id, { ...row, children: [] as typeof rows }])); const roots: Array<(typeof rows)[number] & { children: typeof rows }> = [];
    for (const row of rows) { const node = map.get(row.id)!; if (row.parentId && map.has(row.parentId)) map.get(row.parentId)!.children.push(node); else roots.push(node); } return roots;
  }
  byId(id: string) { return this.prisma.category.findFirstOrThrow({ where: { id, deletedAt: null, isActive: true }, include: categoryInclude }); }
  bySlug(slug: string) { return this.prisma.category.findFirstOrThrow({ where: { slug, deletedAt: null, isActive: true }, include: categoryInclude }); }
  children(id: string) { return this.prisma.category.findMany({ where: { parentId: id, deletedAt: null, isActive: true }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { deletedAt: null } } } }); }
  attributes(id: string) { return this.prisma.categoryAttribute.findMany({ where: { categoryId: id, deletedAt: null, attribute: { deletedAt: null, isActive: true } }, orderBy: { sortOrder: 'asc' }, include: { attribute: { include: { translations: { where: { deletedAt: null } }, options: { where: { deletedAt: null, isActive: true }, orderBy: { sortOrder: 'asc' }, include: { translations: { where: { deletedAt: null } } } } } } } }); }
  brands(id: string) { return this.prisma.categoryBrand.findMany({ where: { categoryId: id, deletedAt: null, brand: { deletedAt: null, isActive: true } }, orderBy: { sortOrder: 'asc' }, include: { brand: { include: { translations: { where: { deletedAt: null } } } } } }); }
  async create(dto: CreateCategoryDto) { if (dto.parentId) await this.ensureCategory(dto.parentId); try { return await this.prisma.category.create({ data: { slug: dto.slug, parentId: dto.parentId ?? null, icon: dto.icon ?? null, imageId: dto.imageId ?? null, sortOrder: dto.sortOrder ?? 0, isActive: dto.isActive ?? true, isFeatured: dto.isFeatured ?? false, requiresModeration: dto.requiresModeration ?? false, listingLifetimeDays: dto.listingLifetimeDays ?? null, translations: { create: dto.translations } }, include: { translations: true } }); } catch { throw new ConflictException('Category slug or translation locale already exists'); } }
  async update(id: string, dto: UpdateCategoryDto) { await this.ensureCategory(id); if (dto.parentId !== undefined) await this.assertValidParent(id, dto.parentId); const translations = dto.translations; const data = { ...dto, parentId: dto.parentId ?? undefined, translations: undefined } as never; return this.prisma.$transaction(async (tx) => { await tx.category.update({ where: { id }, data }); if (translations) for (const item of translations) await tx.categoryTranslation.upsert({ where: { categoryId_locale: { categoryId: id, locale: item.locale } }, update: { name: item.name, seoTitle: item.seoTitle ?? null, seoDescription: item.seoDescription ?? null, deletedAt: null }, create: { categoryId: id, locale: item.locale, name: item.name, seoTitle: item.seoTitle ?? null, seoDescription: item.seoDescription ?? null } }); return tx.category.findUniqueOrThrow({ where: { id }, include: { translations: true } }); }); }
  async remove(id: string, force = false) { await this.ensureCategory(id); const activeChildren = await this.prisma.category.count({ where: { parentId: id, deletedAt: null, isActive: true } }); if (activeChildren && !force) throw new ConflictException('Category has active children; use force to delete the subtree'); const ids = force ? await this.descendantIds(id) : [id]; const now = new Date(); await this.prisma.$transaction([this.prisma.category.updateMany({ where: { id: { in: ids } }, data: { deletedAt: now, isActive: false } }), this.prisma.categoryTranslation.updateMany({ where: { categoryId: { in: ids } }, data: { deletedAt: now } }), this.prisma.categoryAttribute.updateMany({ where: { categoryId: { in: ids } }, data: { deletedAt: now } }), this.prisma.categoryBrand.updateMany({ where: { categoryId: { in: ids } }, data: { deletedAt: now } })]); return { deleted: ids.length }; }
  async restore(id: string) { const category = await this.prisma.category.findUnique({ where: { id } }); if (!category) throw new NotFoundException('Category not found'); if (category.parentId) { const parent = await this.prisma.category.findFirst({ where: { id: category.parentId, deletedAt: null } }); if (!parent) throw new ConflictException('Restore the parent category first'); } await this.prisma.$transaction([this.prisma.category.update({ where: { id }, data: { deletedAt: null, isActive: true } }), this.prisma.categoryTranslation.updateMany({ where: { categoryId: id }, data: { deletedAt: null } })]); return this.prisma.category.findUniqueOrThrow({ where: { id }, include: { translations: true } }); }
  async reorder(dto: ReorderCategoriesDto) { for (const item of dto.items) if (item.parentId !== undefined) await this.assertValidParent(item.id, item.parentId); await this.prisma.$transaction(dto.items.map((item) => this.prisma.category.update({ where: { id: item.id }, data: { sortOrder: item.sortOrder, ...(item.parentId !== undefined ? { parentId: item.parentId } : {}) } }))); return { updated: dto.items.length }; }
  async attachAttribute(categoryId: string, dto: AttachAttributeDto) { await this.ensureCategory(categoryId); await this.prisma.attributeDefinition.findFirstOrThrow({ where: { id: dto.attributeId, deletedAt: null } }); return this.prisma.categoryAttribute.upsert({ where: { categoryId_attributeId: { categoryId, attributeId: dto.attributeId } }, update: { deletedAt: null, required: dto.required ?? null, sortOrder: dto.sortOrder ?? 0 }, create: { categoryId, attributeId: dto.attributeId, required: dto.required ?? null, sortOrder: dto.sortOrder ?? 0 } }); }
  async detachAttribute(categoryId: string, attributeId: string) { const result = await this.prisma.categoryAttribute.updateMany({ where: { categoryId, attributeId, deletedAt: null }, data: { deletedAt: new Date() } }); if (!result.count) throw new NotFoundException('Category attribute not found'); return { deleted: true }; }
  private async ensureCategory(id: string) { const category = await this.prisma.category.findFirst({ where: { id, deletedAt: null } }); if (!category) throw new NotFoundException('Category not found'); return category; }
  private async assertValidParent(id: string, parentId: string) { if (id === parentId) throw new BadRequestException('Category cannot be its own parent'); await this.ensureCategory(parentId); const descendants = await this.descendantIds(id); if (descendants.includes(parentId)) throw new BadRequestException('Category parent would create a cycle'); }
  private async descendantIds(id: string) { const all = await this.prisma.category.findMany({ where: { deletedAt: null }, select: { id: true, parentId: true } }); const result = [id]; for (let i = 0; i < result.length; i++) for (const row of all) if (row.parentId === result[i] && !result.includes(row.id)) result.push(row.id); return result; }
}
