import { readFile } from 'node:fs/promises';
import type { PrismaClient } from '../src/generated/prisma/client.js';
import type { AttributeType } from '../src/generated/prisma/enums.js';
type CategoryNode = { slug: string; name: string; children?: CategoryNode[] };
type Locale = 'ru' | 'en' | 'hy';
const locales: Locale[] = ['ru', 'en', 'hy'];
const loadTree = async (locale: Locale): Promise<CategoryNode[]> => JSON.parse(await readFile(new URL(`../data/categories.${locale}.json`, import.meta.url), 'utf8')) as CategoryNode[];
const flatten = (nodes: CategoryNode[], parentSlug: string | null = null): Array<CategoryNode & { parentSlug: string | null }> => nodes.flatMap((node) => [{ ...node, parentSlug }, ...flatten(node.children ?? [], node.slug)]);

const labels: Record<string, [string, string, string]> = {
  brand: ['Бренд', 'Brand', 'Ապրանքանիշ'], model: ['Модель', 'Model', 'Մոդել'], year: ['Год выпуска', 'Year', 'Թողարկման տարեթիվ'], mileage: ['Пробег', 'Mileage', 'Վազք'], bodyType: ['Тип кузова', 'Body type', 'Թափքի տեսակ'], fuelType: ['Тип топлива', 'Fuel type', 'Վառելիքի տեսակ'], transmission: ['Коробка передач', 'Transmission', 'Փոխանցման տուփ'], driveType: ['Привод', 'Drive type', 'Քարշակման տեսակ'], engineVolume: ['Объём двигателя', 'Engine volume', 'Շարժիչի ծավալ'], color: ['Цвет', 'Color', 'Գույն'], condition: ['Состояние', 'Condition', 'Վիճակ'], vin: ['VIN', 'VIN', 'VIN'], transactionType: ['Тип сделки', 'Transaction type', 'Գործարքի տեսակ'], rooms: ['Количество комнат', 'Rooms', 'Սենյակների քանակ'], totalArea: ['Общая площадь', 'Total area', 'Ընդհանուր մակերես'], floor: ['Этаж', 'Floor', 'Հարկ'], totalFloors: ['Этажей в здании', 'Total floors', 'Շենքի հարկերի քանակ'], buildingType: ['Тип здания', 'Building type', 'Շենքի տեսակ'], renovation: ['Ремонт', 'Renovation', 'Վերանորոգում'], heating: ['Отопление', 'Heating', 'Ջեռուցում'], bathroom: ['Санузел', 'Bathroom', 'Սանհանգույց'], balcony: ['Балкон', 'Balcony', 'Պատշգամբ'], elevator: ['Лифт', 'Elevator', 'Վերելակ'], parking: ['Парковка', 'Parking', 'Կայանատեղի'], storage: ['Память', 'Storage', 'Հիշողություն'], ram: ['Оперативная память', 'RAM', 'Օպերատիվ հիշողություն'], simCount: ['Количество SIM', 'SIM count', 'SIM քարտերի քանակ']
};
const definitions: Array<{ key: string; type: AttributeType; unit?: string; filterable?: boolean; required?: boolean }> = [
  { key: 'brand', type: 'BRAND', filterable: true, required: true }, { key: 'model', type: 'MODEL', filterable: true, required: true }, { key: 'year', type: 'YEAR', filterable: true }, { key: 'mileage', type: 'NUMBER', unit: 'km', filterable: true }, { key: 'bodyType', type: 'SINGLE_SELECT', filterable: true }, { key: 'fuelType', type: 'SINGLE_SELECT', filterable: true }, { key: 'transmission', type: 'SINGLE_SELECT', filterable: true }, { key: 'driveType', type: 'SINGLE_SELECT', filterable: true }, { key: 'engineVolume', type: 'DECIMAL', unit: 'L', filterable: true }, { key: 'color', type: 'COLOR', filterable: true }, { key: 'condition', type: 'SINGLE_SELECT', filterable: true }, { key: 'vin', type: 'TEXT' },
  { key: 'transactionType', type: 'SINGLE_SELECT', filterable: true, required: true }, { key: 'rooms', type: 'NUMBER', filterable: true }, { key: 'totalArea', type: 'DECIMAL', unit: 'm²', filterable: true }, { key: 'floor', type: 'NUMBER', filterable: true }, { key: 'totalFloors', type: 'NUMBER' }, { key: 'buildingType', type: 'SINGLE_SELECT', filterable: true }, { key: 'renovation', type: 'SINGLE_SELECT', filterable: true }, { key: 'heating', type: 'SINGLE_SELECT', filterable: true }, { key: 'bathroom', type: 'SINGLE_SELECT' }, { key: 'balcony', type: 'BOOLEAN' }, { key: 'elevator', type: 'BOOLEAN' }, { key: 'parking', type: 'BOOLEAN', filterable: true },
  { key: 'storage', type: 'SINGLE_SELECT', unit: 'GB', filterable: true }, { key: 'ram', type: 'SINGLE_SELECT', unit: 'GB', filterable: true }, { key: 'simCount', type: 'NUMBER' }
];
const categoryAttributes: Record<string, string[]> = { cars: ['brand','model','year','mileage','bodyType','fuelType','transmission','driveType','engineVolume','color','condition','vin'], apartments: ['transactionType','rooms','totalArea','floor','totalFloors','buildingType','renovation','heating','bathroom','balcony','elevator','parking'], phones: ['brand','model','storage','ram','color','condition','simCount'] };
const brands = [
  { slug: 'toyota', name: 'Toyota', models: ['Camry','Corolla','RAV4'] }, { slug: 'bmw', name: 'BMW', models: ['3 Series','5 Series','X5'] }, { slug: 'mercedes-benz', name: 'Mercedes-Benz', models: ['C-Class','E-Class','GLE'] },
  { slug: 'apple', name: 'Apple', models: ['iPhone 15','iPhone 16','iPhone 17'] }, { slug: 'samsung', name: 'Samsung', models: ['Galaxy S24','Galaxy S25','Galaxy A56'] }, { slug: 'xiaomi', name: 'Xiaomi', models: ['Redmi Note 14','Xiaomi 15','Poco X7'] }
];
export async function seedCatalog(prisma: PrismaClient): Promise<{ categories: number; translations: number; attributes: number; brands: number }> {
  const trees = await Promise.all(locales.map(loadTree)); const flat = trees.map((tree) => flatten(tree)); const byLocale = new Map(locales.map((locale, index) => [locale, new Map(flat[index]!.map((node) => [node.slug, node]))])); const ids = new Map<string, string>();
  for (const node of flat[0]!) { const parentId = node.parentSlug ? (ids.get(node.parentSlug) ?? null) : null; if (node.parentSlug && !parentId) throw new Error(`Missing parent category: ${node.parentSlug}`); const category = await prisma.category.upsert({ where: { slug: node.slug }, update: { parentId, deletedAt: null, isActive: true }, create: { slug: node.slug, parentId, sortOrder: ids.size } }); ids.set(node.slug, category.id); for (const locale of locales) { const translated = byLocale.get(locale)!.get(node.slug)!; await prisma.categoryTranslation.upsert({ where: { categoryId_locale: { categoryId: category.id, locale } }, update: { name: translated.name, deletedAt: null }, create: { categoryId: category.id, locale, name: translated.name } }); } }
  const attributeIds = new Map<string, string>(); for (const [index, definition] of definitions.entries()) { const attribute = await prisma.attributeDefinition.upsert({ where: { key: definition.key }, update: { type: definition.type, filterable: definition.filterable ?? false, required: definition.required ?? false, deletedAt: null, isActive: true }, create: { key: definition.key, type: definition.type, filterable: definition.filterable ?? false, required: definition.required ?? false, sortOrder: index } }); attributeIds.set(definition.key, attribute.id); const translated = labels[definition.key]!; for (const [localeIndex, locale] of locales.entries()) await prisma.attributeTranslation.upsert({ where: { attributeId_locale: { attributeId: attribute.id, locale } }, update: { label: translated[localeIndex]!, unit: definition.unit ?? null, deletedAt: null }, create: { attributeId: attribute.id, locale, label: translated[localeIndex]!, unit: definition.unit ?? null } }); }
  for (const [slug, keys] of Object.entries(categoryAttributes)) { const categoryId = ids.get(slug)!; for (const [sortOrder, key] of keys.entries()) await prisma.categoryAttribute.upsert({ where: { categoryId_attributeId: { categoryId, attributeId: attributeIds.get(key)! } }, update: { sortOrder, deletedAt: null }, create: { categoryId, attributeId: attributeIds.get(key)!, sortOrder } }); }
  for (const item of brands) { const brand = await prisma.brand.upsert({ where: { slug: item.slug }, update: { isActive: true, deletedAt: null }, create: { slug: item.slug } }); for (const locale of locales) await prisma.brandTranslation.upsert({ where: { brandId_locale: { brandId: brand.id, locale } }, update: { name: item.name, deletedAt: null }, create: { brandId: brand.id, locale, name: item.name } }); const categoryId = ids.get(['apple','samsung','xiaomi'].includes(item.slug) ? 'phones' : 'cars')!; await prisma.categoryBrand.upsert({ where: { categoryId_brandId: { categoryId, brandId: brand.id } }, update: { deletedAt: null }, create: { categoryId, brandId: brand.id } }); for (const [sortOrder, modelName] of item.models.entries()) { const slug = modelName.toLowerCase().replace(/[^a-z0-9]+/g, '-'); const model = await prisma.brandModel.upsert({ where: { brandId_slug: { brandId: brand.id, slug } }, update: { deletedAt: null, isActive: true, sortOrder }, create: { brandId: brand.id, slug, sortOrder } }); for (const locale of locales) await prisma.brandModelTranslation.upsert({ where: { modelId_locale: { modelId: model.id, locale } }, update: { name: modelName, deletedAt: null }, create: { modelId: model.id, locale, name: modelName } }); } }
  return { categories: flat[0]!.length, translations: flat[0]!.length * locales.length, attributes: definitions.length, brands: brands.length };
}
